# Generated by Django 3.2.9 on 2021-12-01 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('publication_year', models.PositiveIntegerField(default=None)),
                ('description', models.TextField(default=None, max_length=600)),
                ('genre', models.CharField(choices=[('a', 'Biography'), ('b', 'Business'), ('c', 'Classics'), ('d', 'Comics'), ('e', 'Fantasy'), ('f', 'Fiction'), ('g', 'History'), ('h', 'Horror'), ('i', 'Memoir'), ('j', 'Mystery'), ('k', 'Nonfiction'), ('l', 'Poetry'), ('m', 'Romance'), ('n', 'Science Fiction'), ('o', 'Thriller'), ('p', 'Young Adults')], default=None, max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='authors.author')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
