# Generated by Django 3.2.9 on 2021-12-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Biography', 'Biography'), ('Business', 'Business'), ('Classics', 'Classics'), ('Comics', 'Comics'), ('Fantasy', 'Fantasy'), ('Fiction', 'Fiction'), ('History', 'History'), ('Horror', 'Horror'), ('Memoir', 'Memoir'), ('Mystery', 'Mystery'), ('Nonfiction', 'Nonfiction'), ('Poetry', 'Poetry'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller'), ('Young Adults', 'Young Adults')], default=None, max_length=50),
        ),
    ]
