# Generated by Django 4.0 on 2023-01-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_alter_user_profile_image'),
        ('books', '0005_book_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwt_auth.user'),
        ),
    ]
