# Generated by Django 3.2.9 on 2021-12-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
